services:
  postgres:
    image: postgres:17
    container_name: provaweb-postgres
    environment:
      POSTGRES_DB: provaweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - provaweb_data:/var/lib/postgresql/data

volumes:
  provaweb_data: